config/routes.rb
Rails.application.routes.draw do
  devise_for :users

   root 'users#home'

  resources :page_updates, only: [:create] do
    collection do
      get 'events'
      get 'status_events'
    end
  end

end

app/models/page_update.rb
class PageUpdate < ActiveRecord::Base
  belongs_to :user

  def time_string
    created_at.strftime('Date: %d %B, %Y  |  Time: %H:%M:%S')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :page_updates


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_updates_controller.rb
class PageUpdatesController < ApplicationController
  include ActionController::Live
  before_action :authenticate_user!

  def create
    response.headers['Content-Type'] = 'text/javascript'
    page_update = current_user.page_updates.create(content: params['content'])
    $redis.publish('page_updates.create', { email: page_update.user.email, content: page_update.content, time: page_update.time_string }.to_json )
  end

  def events
    response.headers['Content-Type'] = 'text/event-stream'

    redis = Redis.new
    redis.subscribe('page_updates.create') do |on|
      on.message do |event, data|
        response.stream.write("data: #{data}\n\n")
        response.stream.write("event: custom_alert\ndata: #{data}\n\n")
      end
    end

  rescue IOError
    logger.info 'Stream Closed' # in case if the browser is closed
  ensure
    redis.quit
    response.stream.close
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def home
    @page_updates = PageUpdate.order(created_at: :desc)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_updates_helper.rb
module PageUpdatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Status</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user.present? %>
    <div class="user_creds" style="float: right; padding: 20px; color: #730E15; font-weight: bold;">
      Logged in as <%= current_user.email %>
    </div>
<% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/page_updates/create.js.erb
$('.update-container form textarea').val('');

app/views/users/home.html.erb
<div class="page_container">

  <div class="row">
    <div class="col-md-12 update-container">
      <%= form_tag(page_updates_path, remote: true) do %>
          <%= text_area_tag 'content' %>
          <br />
          <%= submit_tag 'Update', class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="alert_container">
      <div class="sse_alert">
      </div>
    </div>
  </div>

  <div class="row status_container">
    <div class="col-md-12">
      <% @page_updates.each do |single_update| %>
        <div class="row single-update">
          <div class="col-md-2 user-email">
            <%= single_update.user.email %>
          </div>
          <div class="col-md-10">
            <%= single_update.content %>
          </div>
          <div class="col-md-10 ago_time">
            <%= single_update.time_string  %>
          </div>
        </div>

      <% end %>
    </div>
  </div>

</div>